GROQ_API_KEY="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"
# CBUAE Banking Compliance System - Secrets Configuration
# Place this file in .streamlit/secrets.toml

# ===================== AUTHENTICATION =====================
[authentication]
# Admin credentials
admin_username = "admin"
admin_password = "admin123"

# User credentials
compliance_username = "compliance"
compliance_password = "compliance123"

analyst_username = "analyst"
analyst_password = "analyst123"

demo_username = "demo"
demo_password = "demo123"

# JWT Secret for session management
jwt_secret = "your-super-secret-jwt-key-change-this-in-production"
session_timeout = 28800  # 8 hours in seconds

# ===================== MCP CLIENT =====================
[mcp]
server_url = "ws://localhost:8765"
auth_token = "your-mcp-auth-token-here"
timeout = 30
max_retries = 3
reconnect_interval = 5

# ===================== MEMORY AGENT =====================
[memory]
db_path = "banking_memory.db"
vector_dimension = 384
vector_index_path = "banking_vectors.faiss"
encryption_key = "your-32-character-encryption-key-here"

# ===================== REDIS CONFIGURATION =====================
# ===================== REDIS CONFIGURATION =====================
[redis]
redis_host = "localhost"          # Change to your Redis host
redis_port = 6379                 # Default Redis port
redis_db = 0                      # Database number (0-15)
redis_password = ""               # Set password if required
ssl = false                       # Enable for production
socket_timeout = 5                # Connection timeout
socket_connect_timeout = 5        # Connect timeout
max_connections = 20              # Connection pool size

# ===================== REDIS CLUSTER (Optional) =====================
[redis_cluster]
enabled = false
nodes = [
    "redis-node1:6379",
    "redis-node2:6379",
    "redis-node3:6379"
]
# ===================== RETENTION POLICIES =====================
[retention_policies]
[retention_policies.session]
default_ttl = 28800  # 8 hours

[retention_policies.knowledge]
default_ttl = 2592000  # 30 days

[retention_policies.cache]
default_ttl = 3600  # 1 hour

[retention_policies.audit]
default_ttl = 31536000  # 1 year

# ===================== DATABASE CONFIGURATION =====================
[database]
# Main application database
host = "localhost"
port = 5432
name = "cbuae_compliance"
username = "postgres"
password = "your-db-password"
ssl_mode = "prefer"
pool_size = 10
max_overflow = 20

# ===================== LLM CONFIGURATION =====================
[llm]
# OpenAI Configuration
openai_api_key = "your-openai-api-key"
openai_model = "gpt-4"
openai_max_tokens = 4000

# Azure OpenAI Configuration (alternative)
azure_openai_endpoint = "https://your-resource.openai.azure.com/"
azure_openai_key = "your-azure-openai-key"
azure_openai_version = "2023-12-01-preview"

# Anthropic Configuration (alternative)
anthropic_api_key = "your-anthropic-api-key"

# ===================== CBUAE API CONFIGURATION =====================
[cbuae_api]
base_url = "https://api.cbuae.gov.ae"
api_key = "your-cbuae-api-key"
timeout = 30
rate_limit = 100  # requests per minute

# ===================== CLOUD STORAGE =====================
[cloud_storage]
# AWS S3 Configuration
aws_access_key_id = "your-aws-access-key"
aws_secret_access_key = "your-aws-secret-key"
aws_region = "us-east-1"
s3_bucket = "cbuae-compliance-data"

# Azure Blob Storage Configuration
azure_storage_account = "your-storage-account"
azure_storage_key = "your-storage-key"
azure_container = "compliance-data"

# Google Cloud Storage Configuration
gcp_project_id = "your-gcp-project"
gcp_service_account_key = "path/to/service-account-key.json"
gcs_bucket = "cbuae-compliance-data"

# ===================== EMAIL CONFIGURATION =====================
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
smtp_username = "your-email@domain.com"
smtp_password = "your-email-password"
use_tls = true

# ===================== LOGGING CONFIGURATION =====================
[logging]
level = "INFO"
file_path = "logs/cbuae_compliance.log"
max_file_size = "10MB"
backup_count = 5
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# ===================== SECURITY CONFIGURATION =====================
[security]
# Encryption settings
fernet_key = "your-fernet-encryption-key-32-bytes"
password_salt = "your-password-salt"

# HTTPS settings
ssl_cert_path = "/path/to/ssl/cert.pem"
ssl_key_path = "/path/to/ssl/key.pem"

# CORS settings
allowed_origins = ["http://localhost:8501", "https://your-domain.com"]

# ===================== EXTERNAL SERVICES =====================
[external_services]
# Banking Core System
core_banking_url = "https://core-banking-api.bank.ae"
core_banking_token = "your-core-banking-token"

# Regulatory Reporting System
regulatory_api_url = "https://regulatory-api.cbuae.gov.ae"
regulatory_api_key = "your-regulatory-api-key"

# KYC Service
kyc_service_url = "https://kyc-service.compliance.ae"
kyc_service_token = "your-kyc-service-token"

# ===================== AGENT CONFIGURATION =====================
[agents]
# Dormancy Agents
dormancy_enabled = true
dormancy_timeout = 300  # 5 minutes
dormancy_max_parallel = 5

# Compliance Agents
compliance_enabled = true
compliance_timeout = 600  # 10 minutes
compliance_max_parallel = 10

# Processing Agents
processing_enabled = true
processing_chunk_size = 1000
processing_timeout = 180  # 3 minutes

# ===================== MONITORING & ALERTING =====================
[monitoring]
# Prometheus metrics
prometheus_enabled = true
prometheus_port = 9090

# Health check endpoints
health_check_enabled = true
health_check_interval = 60  # seconds

# Alerting
alert_webhook_url = "https://hooks.slack.com/your-webhook"
alert_email = "alerts@your-domain.com"

# ===================== DEVELOPMENT SETTINGS =====================
[development]
debug_mode = false
log_sql_queries = false
enable_profiling = false
mock_external_apis = false

# ===================== BACKUP CONFIGURATION =====================
[backup]
enabled = true
schedule = "0 2 * * *"  # Daily at 2 AM
retention_days = 30
backup_location = "/backup/cbuae-compliance"
encrypt_backups = true

# ===================== RATE LIMITING =====================
[rate_limiting]
requests_per_minute = 1000
requests_per_hour = 10000
burst_size = 100
enable_rate_limiting = true

# ===================== FEATURE FLAGS =====================
[features]
enable_llm_enhancement = true
enable_real_time_processing = true
enable_advanced_analytics = true
enable_export_all_formats = true
enable_audit_logging = true

# ===================== CACHING =====================
[caching]
enabled = true
default_ttl = 3600  # 1 hour
max_size = "100MB"
cache_type = "redis"  # redis, memory, or file

# ===================== STREAMLIT SPECIFIC =====================
[streamlit]
# Custom theme colors
primary_color = "#1f4e79"
background_color = "#ffffff"
secondary_background_color = "#f0f8ff"
text_color = "#262730"

# Performance settings
max_upload_size = 200  # MB
cache_ttl = 3600  # seconds
enable_caching = true